version: '3'

services:
  antrade:
    build: ./
    container_name: telegram_interface
    command: ["python3", "main.py"]
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env